version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "weekly"  # Check for updates weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
