name: Keep the repo alive
on:
  schedule:
    - cron: "45 19 * * *"
  push:
  fork:
  status:
  issues:

jobs:
  cronjob-based-github-action:
    name: Cronjob based github action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@v1
        with:
          committer_username: ${{ github.repository_owner }}
          committer_email: ${{ github.repository_owner }}@users.noreply.github.com
