# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Login to Kaggle
      uses: osbm/kaggle-login@v2.3
      with:
        KAGGLE_USERNAME: ${{ github.repository_owner }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
    - name: Run app
      run: |
        mkdir -p /tmp/out
        script_path="$PWD/main.py"
        ln -s "$PWD/symbols.txt" /tmp/out/symbols.txt
        pushd /tmp/out
        kaggle datasets download -w --unzip --force ${{ github.repository }}
        ls -lah
        python $script_path
        popd

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: yahoodata
        path: /tmp/out/
        retention-days: 1

  upload_to_kaggle:
    runs-on: ubuntu-latest
    needs: [run]
    if: ${{ github.actor }} == ${{ github.repository_owner }}
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: yahoodata
    - name: Display structure of downloaded files
      run: ls -R
    - name: Upload datasets
      uses: jaimevalero/push-kaggle-dataset@v3
      env:
        KAGGLE_USERNAME: ${{ github.repository_owner }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

      with:
        title: "Yahoo Financial data"
        subtitle: "Yahoo Financial data"
        description: "## Example of dataset syncronized by github actions <br/>Source https://github.com/jaimevalero/test-actions and https://github.com/jaimevalero/push-kaggle-dataset <br/> "
        files: |
          *.csv.xz
        is_public: false

