name: Data Processing and Kaggle Upload Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "33 18 * * *"

env:
  PYTHON_VERSION: "3.11"

permissions:
  contents: read

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor || github.repository_owner }}
  cancel-in-progress: ${{ (github.event_name == 'push' && github.base_ref == 'main' || github.event_name == 'schedule') && github.actor == github.repository_owner }}

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --exit-zero --select=E,F --show-source --statistics
          # Exit on syntax errors and undefined names
          exit 0  # Treats all errors as warnings (consider a stricter exit code)


      - name: Lint another time with flake8
        run: |
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests
        if: false
        run: |
          pytest

  download-data:
    runs-on: ubuntu-latest
    needs: [ lint-and-test ]  # Only run after successful lint and test

    steps:
      - uses: actions/checkout@v3

      - name: Login to Kaggle
        if: ${{ github.actor == github.repository_owner }}
        uses: osbm/kaggle-login@v2.3
        with:
          KAGGLE_USERNAME: ${{ github.repository_owner }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

      - name: Download data
        if: ${{ github.actor == github.repository_owner }}
        uses: Wandalen/wretry.action@v3.5.0
        with:
          attempt_limit: 10
          attempt_delay: 60000
          command: |
            mkdir -p /tmp/out
            cd /tmp/out
            kaggle datasets download -w --unzip --force ${{ github.repository }}

      - name: Check Downloaded Files
        if: ${{ github.actor == github.repository_owner }}
        run: |
          cd /tmp/out/
          # Check for at least 2 downloaded CSV.XZ files
          if [ $(find . -type f -name "*.csv.xz" -depth | wc -l) -lt 2 ]; then
            echo "Error: Less than 2 downloaded CSV.XZ files found!"
            exit 1
          fi

          # Check for existence and size of BTC-USD.csv.xz
          if [ ! -f "./BTC-USD.csv.xz" -o "$(stat -c %s ./BTC-USD.csv.xz)" -eq 0 ]; then
            echo "Error: BTC-USD.csv.xz not found or has zero size!"
            exit 1
          fi

          echo "Downloaded data seems valid!"

      - name: Upload Artifact
        if: ${{ github.actor == github.repository_owner }}
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-data
          path: /tmp/out/
          retention-days: 90
  run:

    runs-on: ubuntu-latest
    needs: [ download-data ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Login to Kaggle
        if: ${{ github.actor == github.repository_owner }}
        uses: osbm/kaggle-login@v2.3
        with:
          KAGGLE_USERNAME: ${{ github.repository_owner }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}


      - name: mkdir tmp
        run: |
          mkdir -p /tmp/out

      - uses: actions/download-artifact@v3
        if: ${{ github.actor == github.repository_owner }}
        with:
          name: downloaded-data
          path: /tmp/out/

      - name: Display structure of downloaded files
        run: ls -R /tmp/out

      - name: Check Downloaded Files
        if: ${{ github.actor == github.repository_owner }}
        run: |
          cd /tmp/out/
          # Check for at least 2 downloaded CSV.XZ files
          if [ $(find . -type f -name "*.csv.xz" -depth | wc -l) -lt 2 ]; then
            echo "Error: Less than 2 downloaded CSV.XZ files found!"
            exit 1
          fi

          # Check for existence and size of BTC-USD.csv.xz
          if [ ! -f "./BTC-USD.csv.xz" -o "$(stat -c %s ./BTC-USD.csv.xz)" -eq 0 ]; then
            echo "Error: BTC-USD.csv.xz not found or has zero size!"
            exit 1
          fi

          echo "Downloaded data seems valid!"

      - name: Get BTC-USD.csv.xz stats before running script
        if: ${{ github.actor == github.repository_owner }}
        run: |
          btc_stats_before=$(stat -c %y,%s /tmp/out/BTC-USD.csv.xz 2>/dev/null)
          echo "$btc_stats_before" > /tmp/btc_stats_before.txt

      - name: Run app
        run: |
          script_path="$PWD/main.py"
          ln -s "$PWD/symbols.txt" /tmp/out/symbols.txt
          pushd /tmp/out
          ls -lah
          python $script_path
          rm -rf symbols.txt
          popd

      - name: Check BTC-USD.csv.xz stats after running script
        if: ${{ github.actor == github.repository_owner }}
        run: |
          btc_stats_after=$(stat -c %y,%s /tmp/out/BTC-USD.csv.xz 2>/dev/null)
          btc_stats_before=$(cat /tmp/btc_stats_before.txt)
          if [ $? -eq 0 ]; then
            echo "BTC-USD.csv.xz modification time (after): $btc_stats_after"
            # Extract modification time and size from each variable
            before_mtime=$(echo "$btc_stats_before" | cut -d',' -f1)
            before_size=$(echo "$btc_stats_before" | cut -d',' -f2)
            after_mtime=$(echo "$btc_stats_after" | cut -d',' -f1)
            after_size=$(echo "$btc_stats_after" | cut -d',' -f2)

            # Compare modification time and size
            if [[ "$before_mtime" == "$after_mtime" || "$before_size" == "$after_size" ]]; then
              echo "Error: BTC-USD.csv.xz not modified or size changed unexpectedly!"
              exit 1
            fi
          else
            echo "Error: BTC-USD.csv.xz not found after running script."
            exit 1
          fi

      - name: Check Created Files
        run: |
          cd /tmp/out/
          # Check for at least 2 created CSV.XZ files
          if [ $(find . -type f -name "*.csv.xz" -depth | wc -l) -lt 2 ]; then
            echo "Error: Less than 2 created CSV.XZ files found!"
            exit 1
          fi

          # Check for existence and size of BTC-USD.csv.xz
          if [ ! -f "./BTC-USD.csv.xz" -o "$(stat -c %s ./BTC-USD.csv.xz)" -eq 0 ]; then
            echo "Error: BTC-USD.csv.xz not found or has zero size!"
            exit 1
          fi

          echo "Created data seems valid!"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: yahoodata
          path: /tmp/out/
          retention-days: 1

  upload_to_kaggle:
    runs-on: ubuntu-latest
    needs: [ run ]
    if: ${{ github.actor == github.repository_owner && (github.event_name == 'push' && github.base_ref == 'main' || github.event_name == 'schedule') }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: yahoodata
      - name: Display structure of downloaded files
        run: ls -R
      - name: Upload datasets
        uses: jaimevalero/push-kaggle-dataset@v3
        env:
          KAGGLE_USERNAME: ${{ github.repository_owner }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

        with:
          title: "Yahoo Financial data"
          subtitle: "Yahoo Financial data"
          description: |
            ## This dataset contains minutely stock data price of various market in a csv file format

            This dataset was automatically uploaded from a GitHub Actions workflow 
            running in the ${{ github.repository }} repository. 

            Feel free to explore and use this data for your analysis!
          files: |
            *.csv.xz
          is_public: false

